import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers as ThemeProviderUtil } from "@/utils/ThemeProviderUtil";
import ThemeToggle from "@/components/layout/ThemeToggle";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeProviderUtil>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <nav className="flex flex-col items-center sticky top-0 z-50 w-full my-4">
            <Navbar />
          </nav>
          <ThemeToggle />
          <main className="min-h-screen">
            {children}
          </main>
          <footer>
            <Footer />
          </footer>
        </body>
      </ThemeProviderUtil>
    </html>
  );
}
